# Generated by Django 5.1.1 on 2025-02-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('reasoning', models.TextField()),
                ('chart', models.ImageField(blank=True, null=True, upload_to='prediction_charts/')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.stock')),
            ],
        ),
    ]
